name: Lottery
main: net.erbros.Lottery.Lottery
version: 0.6.1
author: Erbros
website: www.erbros.net
commands:
  lottery:
    description: Provides access to Permissions commands and information.
    permission: lottery.buy
    usage: |
           /<command>