config:
  # Set this option to true if your using ANY supported economy system
    useiConomy: false
  # Cost per ticket     
    cost: 5
  # If you aren't using an economy system, which item is used for currency
    material: 266
    
  # How long between draws  
    hours: 2   
  # Should we publicly broadcast when someone buys a ticket?
    broadcastBuying: true  
  # At how many seconds remaining should we append time till draw.
    broadcastBuyingTime: 120
  # Should we show lottery status on player join?  
    welcomeMessage: true
    
  # Should we clear 'extra' amount each draw
    clearExtraInPot: true    
  # What percentage of ticket sales is the winner awarded
    netPayout: 100
  # If the net payout is between 0-100 where should the remaining payout go?
    taxTarget: ""
  # How many tickets can each player buy? 
    maxTicketsEachUser: 1
  # Use this option to enable fixed ticket mode.  Setting this will cause rollovers.  
    numberOfTicketsAvailable: 0
      
    buyingExtend:
      # Should the next draw timer be extended if someone buys a ticket close to the draw?
        enabled: true
      # How many seconds remaining count as close to the draw
        secondsRemaining: 30
      # The minimum amount to extend by
        extendBase: 15
      # What multiplier should be used when extending by tickets.
      # Set to 0 to just use base. Extend by: base + (multiplier * sqrt(ticketNumber))
        extendMultiplier: 1.5
    
    nextexec: 0
    extraInPot: 0
    jackpot: 0
    debug: false
message:
    welcome: '&6[LOTTERY] &fDraw in: &c%drawLong%'