config:
    cost: 5
    hours: 24
    nextexec: 0
    material: 266
    useiConomy: false
    broadcastBuying: true
    welcomeMessage: true
    extraInPot: 0
    clearExtraInPot: true
    netPayout: 100
    maxTicketsEachUser: 1
    numberOfTicketsAvailable: 0
    jackpot: 0
    debug: false
    jackpotAccount: ''
message:
    welcome: '&6[LOTTERY] &fDraw in: &c%drawLong%'